spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/permission_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
  cloud:
    openfeign:
      okhttp:
        # 开启okhttp client
        enabled: true
      httpclient:
        # 设置httpclient的连接超时时间，默认是2s
        connection-timeout: 2000
        # 设置连接池最大大小，默认200
        max-connections: 200
        ok-http:
          # 设置okhttp的全局读超时时间，默认是60s
          read-timeout: 60000

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/fun/pullock/permission/core/repository/mapper/*.xml
  type-aliases-package: fun.pullock.permission.core.repository.model